# global path ~/.config/ruff/ruff.toml (~/Library/Application Support/ruff/ruff.toml)
# full lint: ruff check <path>
# sort imports in one file: ruff check --select I --fixable I --fix <file_path>
# format: ruff format --diff <path>

src = ["src"]
output-format = "grouped"
line-length = 80
target-version = "py311"
fix = false
indent-width = 4

exclude = [".git*", ".mypy*", ".ruff*", "venv"]

[lint]
ignore = [
    "ANN002", "ANN003", "ANN101", "ANN102",
    "COM812",
    "D100", "D104", "D107", "D203", "D212",
    "RUF001", "RUF002", "RUF003",
    "TRY003",
    "S101",
]
select = ["ALL"]
task-tags = []

[lint.flake8-annotations]
mypy-init-return = true

[lint.flake8-builtins]
builtins-ignorelist = ["id"]

[lint.flake8-pytest-style]
fixture-parentheses = true
mark-parentheses = true
parametrize-names-type = "tuple"
parametrize-values-row-type = "list"

[lint.isort]
case-sensitive = false
combine-as-imports = true
extra-standard-library = []

[lint.mccabe]
max-complexity=5

[lint.pylint]
max-args = 5

[lint.per-file-ignores]
"__init__.py" = ["F401"]
"*test*.py" = ["ANN001", "ANN201", "ANN202", "D", "N802", "S101"]

[lint.pydocstyle]
convention = "google"

[format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "lf"
exclude = []
